version: '3'

services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/portainer/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.ci.${BASE_DOMAIN}`)"
      - "traefik.http.routers.portainer.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.portainer.entrypoints=websecure"
networks:
  default:
    external:
      name: traefik
